### PR TITLE
fix typo on Client API putTemplate, was putTempalte

### PR DESCRIPTION
**Pull request by gszr**

### CODE REVIEW

**Comment by DhavalKapil** [comment]
Thanks :)

**Comment by pmusa** [comment]
Maybe we should add some test here :)

**Comment by DhavalKapil** [comment]
You mean test for every API function in Client.lua?

**Comment by pmusa** [comment]
Missing a typo like that is not good. How can we test it and make sure it does not happen?

**Comment by DhavalKapil** [comment]
Maybe comparing methods in src/elasticsearch/*.lua with the ones in https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/main/resources/rest-api-spec/api ?

**Comment by pmusa** [comment]
Sounds like an option.

**Pull request merged**
